# Generated by Django 4.0.3 on 2022-03-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_relation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_person1', to='operations.person', verbose_name='Person 1'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_person2', to='operations.person', verbose_name='Person 2'),
        ),
    ]
