# Generated by Django 4.0.3 on 2022-03-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_relation_person1_alter_relation_person2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together=set(),
        ),
    ]
