# Generated by Django 4.0.3 on 2022-03-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_relation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('person1', 'relation', 'person2')},
        ),
    ]
