# Generated by Django 4.0.3 on 2022-03-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_alter_relation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='relation',
            field=models.CharField(choices=[('Father', 'Father'), ('Brother', 'Brother'), ('Child', 'Child')], max_length=12, verbose_name='Relation'),
        ),
    ]
